<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Backend login' => '@@管理登录@@',
  'Backend site' => '@@管理入口@@',
  'Frontend site' => '@@网站首页@@',
  'Manage CatalogNode' => '@@管理栏目@@',
  'update' => '@@修改@@',
  'Plugin' => '模块插件',
  'Page' => '单页',
  'Create Singlepagecatalog' => '添加单页栏目',
  'Create ArticleCatalog' => '添加文章栏目',
  'Create Article' => '添加文章',
  'Create File' => '添加文件',
  'Create Images' => '添加图集',
  'Create Picture' => '添加图片',
  'Create Catalog' => '添加栏目',
  'Create FileCatalog' => '添加文件栏目',
  'Create ImagesCatalog' => '添加图集栏目',
  'Create Mould' => '添加模型',
  'Create PictureCatalog' => '添加图片栏目',
  'FrontendLogin' => '用户登录',
  'Home' => '首页',
  'Login' => '登录',
  'Logout' => '退出',
  'Manage Article' => '管理文章',
  'Manage File' => '管理文件',
  'Manage Images' => '管理图集',
  'Manage Picture' => '管理图片',
  'Manage Catalog' => '管理栏目',
  'Manage Mould' => '管理模型',
  'Manage Upload' => '管理附件',
  'Article' => '文章',
  'Catalog' => '栏目分类',
  'File' => '文件',
  'Images' => '图集',
  'Picture' => '图片',
  'Right' => '权限管理',
  'Attachment' => '附件管理',
);
